version: '3.4'

services:
  webapplicationwithdocker:
    image: ${DOCKER_REGISTRY-}webapplicationwithdocker
    build:
      context: .
      dockerfile: WebApplicationWithDocker/Dockerfile
  mssql:
    image: mcr.microsoft.com/mssql/server:2019-latest
    environment:
    - ACCEPT_EULA=Y
    - SA_PASSWORD=myStrongPassword1!
    ports:
    - "1433:1433"